// src/app/add-player/add-player.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { newStats, Player } from '../../shared/interfaces/player.interface';
import { ApiService } from '../../shared/services/api.service';
import { CustomizedButton } from '../../components/customized-button/customized-button';
import { PlayersState } from '../../store/players/players.state';
import { Store } from '@ngrx/store';
import * as PlayersActions from '../../store/players/players.actions';

@Component({
  selector: 'app-add-player',
  templateUrl: './add-player.html',
  styleUrls: ['./add-player.css'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    CustomizedButton,
  ]
})
export class AddPlayer {
  playerName: string = '';
  selectedEmoji: string = '🚀';
  emojis: string[] = ['🚀', '👾', '✈️', '👩‍✈️', '🛰️', '🧑‍🚀',  '🛸', '☄️', '👽', '🚁', '🔭', '🪐'];

  constructor(
    private router: Router,
    private apiService: ApiService,
    private store: Store<PlayersState>,
  ) { }

  savePlayer(): void {
    if (this.playerName.trim() === '') {
      alert('Player name cannot be empty!');
      return;
    }

    const newPlayer: Player = {
      id: null, // ID will be generated by the backend
      name: this.playerName.trim(),
      icon: this.selectedEmoji,
      stats: newStats // Initialize stats with default values
    };

    this.apiService.createPlayer(newPlayer).subscribe({
      next: (createdPlayer) => {
        this.store.dispatch(PlayersActions.markPlayersStale());
        this.router.navigate(['/rps-play', createdPlayer.id]);
      },
      error: (error) => {
        if (error.status === 409) {
        } else {
        }
      }
    });
  }

  backToMenu(): void {
    this.router.navigate(['/']);
  }
}