/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Data Transfer Object for Leaderboard Player Stats displayed on the Leaderboard.
 */
export interface LeaderboardPlayerStatsDto {

  /**
   * Total number of games played by the player
   */
  gamesPlayed: number;

  /**
   * Emoji icon representing the player
   */
  icon: string;

  /**
   * Unique identifier of the player
   */
  id: number;

  /**
   * Name of the player
   */
  name: string;

  /**
   * Calculated score based on Wilson Score Interval, used for ranking
   */
  score: number;

  /**
   * Win percentage of the player
   */
  winPercentage: number;
}
