/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PlayerStats } from '../models/player-stats';

/**
 * Represents a player in the RPS game
 */
export interface Player {

  /**
   * An emoji or icon representing the player
   */
  icon: string;

  /**
   * Unique ID of the player
   */
  id?: number;

  /**
   * The player's chosen name
   */
  name: string;
  stats: PlayerStats;
}
