/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detailed game statistics for a player
 */
export interface PlayerStats {

  /**
   * History of computer's choices against this player
   */
  computerHistory: Array<'rock' | 'paper' | 'scissors' | 'well'>;

  /**
   * The computer's current score (points from player's losses)
   */
  computerScore: number;

  /**
   * History of player's choices (e.g., 'rock', 'paper')
   */
  playerHistory: Array<'rock' | 'paper' | 'scissors' | 'well'>;

  /**
   * The player's current score (points for wins)
   */
  playerScore: number;

  /**
   * Total number of rounds played by this player
   */
  totalRounds: number;
}
