/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Summary of a player's basic information
 */
export interface PlayerSimplifiedDto {

  /**
   * Icon representing the player
   */
  icon: string;

  /**
   * Unique identifier of the player
   */
  id: number;

  /**
   * Name of the player
   */
  name: string;
}
