/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createPlayer } from '../fn/player-management/create-player';
import { CreatePlayer$Params } from '../fn/player-management/create-player';
import { getAllPlayers } from '../fn/player-management/get-all-players';
import { GetAllPlayers$Params } from '../fn/player-management/get-all-players';
import { getDashboardStats } from '../fn/player-management/get-dashboard-stats';
import { GetDashboardStats$Params } from '../fn/player-management/get-dashboard-stats';
import { getPlayerById } from '../fn/player-management/get-player-by-id';
import { GetPlayerById$Params } from '../fn/player-management/get-player-by-id';
import { LeaderboardPlayerStatsDto } from '../models/leaderboard-player-stats-dto';
import { Player } from '../models/player';
import { PlayerSimplifiedDto } from '../models/player-simplified-dto';
import { PlayerStats } from '../models/player-stats';
import { resetPlayerStats } from '../fn/player-management/reset-player-stats';
import { ResetPlayerStats$Params } from '../fn/player-management/reset-player-stats';
import { updatePlayerStats } from '../fn/player-management/update-player-stats';
import { UpdatePlayerStats$Params } from '../fn/player-management/update-player-stats';


/**
 * Endpoints for creating and retrieving players
 */
@Injectable({ providedIn: 'root' })
export class PlayerManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updatePlayerStats()` */
  static readonly UpdatePlayerStatsPath = '/api/players/{id}/stats';

  /**
   * Update player's stats.
   *
   * Update a player's stats from a game round.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePlayerStats()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePlayerStats$Response(params: UpdatePlayerStats$Params, context?: HttpContext): Observable<StrictHttpResponse<PlayerStats>> {
    return updatePlayerStats(this.http, this.rootUrl, params, context);
  }

  /**
   * Update player's stats.
   *
   * Update a player's stats from a game round.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePlayerStats$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePlayerStats(params: UpdatePlayerStats$Params, context?: HttpContext): Observable<PlayerStats> {
    return this.updatePlayerStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<PlayerStats>): PlayerStats => r.body)
    );
  }

  /** Path part for operation `resetPlayerStats()` */
  static readonly ResetPlayerStatsPath = '/api/players/{id}/reset-stats';

  /**
   * Reset player's score.
   *
   * Resets the wins and games played for a specific player to zero. Acting as a 'new' player for ranking purposes.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resetPlayerStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  resetPlayerStats$Response(params: ResetPlayerStats$Params, context?: HttpContext): Observable<StrictHttpResponse<Player>> {
    return resetPlayerStats(this.http, this.rootUrl, params, context);
  }

  /**
   * Reset player's score.
   *
   * Resets the wins and games played for a specific player to zero. Acting as a 'new' player for ranking purposes.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resetPlayerStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  resetPlayerStats(params: ResetPlayerStats$Params, context?: HttpContext): Observable<Player> {
    return this.resetPlayerStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<Player>): Player => r.body)
    );
  }

  /** Path part for operation `getAllPlayers()` */
  static readonly GetAllPlayersPath = '/api/players';

  /**
   * Get all registered players.
   *
   * Retrieves a list of all existing players in the game.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllPlayers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPlayers$Response(params?: GetAllPlayers$Params, context?: HttpContext): Observable<StrictHttpResponse<PlayerSimplifiedDto>> {
    return getAllPlayers(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all registered players.
   *
   * Retrieves a list of all existing players in the game.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllPlayers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPlayers(params?: GetAllPlayers$Params, context?: HttpContext): Observable<PlayerSimplifiedDto> {
    return this.getAllPlayers$Response(params, context).pipe(
      map((r: StrictHttpResponse<PlayerSimplifiedDto>): PlayerSimplifiedDto => r.body)
    );
  }

  /** Path part for operation `createPlayer()` */
  static readonly CreatePlayerPath = '/api/players';

  /**
   * Create a new player.
   *
   * Registers a new player in the game with a unique name and an optional icon.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createPlayer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPlayer$Response(params: CreatePlayer$Params, context?: HttpContext): Observable<StrictHttpResponse<Player>> {
    return createPlayer(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new player.
   *
   * Registers a new player in the game with a unique name and an optional icon.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createPlayer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPlayer(params: CreatePlayer$Params, context?: HttpContext): Observable<Player> {
    return this.createPlayer$Response(params, context).pipe(
      map((r: StrictHttpResponse<Player>): Player => r.body)
    );
  }

  /** Path part for operation `getPlayerById()` */
  static readonly GetPlayerByIdPath = '/api/players/{id}';

  /**
   * Get player by ID.
   *
   * Retrieves a single player's details by their ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPlayerById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPlayerById$Response(params: GetPlayerById$Params, context?: HttpContext): Observable<StrictHttpResponse<Player>> {
    return getPlayerById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get player by ID.
   *
   * Retrieves a single player's details by their ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPlayerById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPlayerById(params: GetPlayerById$Params, context?: HttpContext): Observable<Player> {
    return this.getPlayerById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Player>): Player => r.body)
    );
  }

  /** Path part for operation `getDashboardStats()` */
  static readonly GetDashboardStatsPath = '/api/players/leaderboard-stats';

  /**
   * Get Leaderboard.
   *
   * Retrieves the Leaderboard by Wilson Score.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDashboardStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDashboardStats$Response(params?: GetDashboardStats$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaderboardPlayerStatsDto>> {
    return getDashboardStats(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Leaderboard.
   *
   * Retrieves the Leaderboard by Wilson Score.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDashboardStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDashboardStats(params?: GetDashboardStats$Params, context?: HttpContext): Observable<LeaderboardPlayerStatsDto> {
    return this.getDashboardStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeaderboardPlayerStatsDto>): LeaderboardPlayerStatsDto => r.body)
    );
  }

}
